// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Demo = require("../src/demo.js");
var Jest = require("bs-jest/lib/js/src/jest.js");

describe("Medium validation", (function () {
        return Jest.test("should demonstrate a test a reason", (function () {
                      return Jest.ExpectJs[/* toEqual */11]("expectedOutput")(Jest.ExpectJs[/* expect */0](Demo.doSomething("withArgs")));
                    }));
      }));

/*  Not a pure module */
