// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Body                              = require("./body.js");
var ReactDOMRe                        = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact                       = require("reason-react/lib/js/src/reasonReact.js");
var Director$slashbuild$slashdirector = require("director/build/director");

function renderForRoute(route, router) {
  return ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Body.make(route, router, /* array */[])), "root");
}

var router = new Director$slashbuild$slashdirector.Router({
      "/": "root",
      "/home": "home",
      "/register": "register",
      "/login": "login",
      "/settings": "settings",
      "/article/create": "article_create",
      "/article/edit": "article_edit",
      "/article": "article"
    });

var handlers = {
  root: (function () {
      return renderForRoute(/* Home */0, router);
    }),
  home: (function () {
      return renderForRoute(/* Home */0, router);
    }),
  register: (function () {
      return renderForRoute(/* Register */1, router);
    }),
  login: (function () {
      return renderForRoute(/* Login */2, router);
    }),
  settings: (function () {
      return renderForRoute(/* Settings */3, router);
    }),
  article_create: (function () {
      return renderForRoute(/* CreateArticle */5, router);
    }),
  article_edit: (function () {
      return renderForRoute(/* EditArticle */6, router);
    }),
  article: (function () {
      return renderForRoute(/* Article */4, router);
    })
};

router.configure({
      html5history: /* true */1,
      resource: handlers
    });

router.init("/");

exports.renderForRoute = renderForRoute;
exports.router         = router;
exports.handlers       = handlers;
/* router Not a pure module */
