// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Body                              = require("./body.js");
var ReactDOMRe                        = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact                       = require("reason-react/lib/js/src/reasonReact.js");
var Director$slashbuild$slashdirector = require("director/build/director");

function renderForRoute(route) {
  return ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Body.make(route, /* array */[])), "main-body");
}

var router = new Director$slashbuild$slashdirector.Router({
      "/": renderForRoute(/* Home */0),
      "/register": renderForRoute(/* Register */1),
      "/login": renderForRoute(/* Login */2)
    });

router.configure({
      html5history: /* true */1
    });

router.init("/");

exports.renderForRoute = renderForRoute;
exports.router         = router;
/* router Not a pure module */
