// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Article");

function show(prim) {
  return prim;
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "article-page"
                }, React.createElement("div", {
                      className: "banner"
                    }, React.createElement("div", {
                          className: "container"
                        }, React.createElement("h1", undefined, "How to build webapps that scale"), React.createElement("div", {
                              className: "article-meta"
                            }, React.createElement("a", {
                                  href: ""
                                }, React.createElement("img", {
                                      src: "http://i.imgur.com/Qr71crq.jpg"
                                    })), React.createElement("div", {
                                  className: "info"
                                }, React.createElement("a", {
                                      className: "author",
                                      href: ""
                                    }, "Eric Simons"), React.createElement("span", {
                                      className: "date"
                                    }, "January 20th")), React.createElement("button", {
                                  className: "btn btn-sm btn-outline-secondary"
                                }, React.createElement("i", {
                                      className: "ion-plus-round"
                                    }), "&nbsp;", "Follow Eric Simons", React.createElement("span", {
                                      className: "counter"
                                    }, "(10)")), "&nbsp;&nbsp;", React.createElement("button", {
                                  className: "btn btn-sm btn-outline-primary"
                                }, React.createElement("i", {
                                      className: "ion-heart"
                                    }), "&nbsp;", "Favorite Post", React.createElement("span", {
                                      className: "counter"
                                    }, "(29)"))))), React.createElement("div", {
                      className: "container page"
                    }, React.createElement("div", {
                          className: "row article-content"
                        }, React.createElement("div", {
                              className: "col-md-12"
                            }, React.createElement("p", undefined, "Web development technologies have evolved at an incredible clip over the past few years."), React.createElement("h2", {
                                  id: "introducing-ionic"
                                }, "Introducing RealWorld."), React.createElement("p", undefined, "It's a great solution for learning how other frameworks work."))), React.createElement("hr", undefined), React.createElement("div", {
                          className: "article-actions"
                        }, React.createElement("div", {
                              className: "article-meta"
                            }, React.createElement("a", {
                                  href: "profile.html"
                                }, React.createElement("img", {
                                      src: "http://i.imgur.com/Qr71crq.jpg"
                                    })), React.createElement("div", {
                                  className: "info"
                                }, React.createElement("a", {
                                      className: "author",
                                      href: ""
                                    }, "Eric Simons"), React.createElement("span", {
                                      className: "date"
                                    }, "January 20th")), React.createElement("button", {
                                  className: "btn btn-sm btn-outline-secondary"
                                }, React.createElement("i", {
                                      className: "ion-plus-round"
                                    }), "&nbsp;", "Follow Eric Simons", React.createElement("span", {
                                      className: "counter"
                                    }, "(10)")), "&nbsp;", React.createElement("button", {
                                  className: "btn btn-sm btn-outline-primary"
                                }, React.createElement("i", {
                                      className: "ion-heart"
                                    }), "&nbsp;", "Favorite Post", React.createElement("span", {
                                      className: "counter"
                                    }, "(29)")))), React.createElement("div", {
                          className: "row"
                        }, React.createElement("div", {
                              className: "col-xs-12 col-md-8 offset-md-2"
                            }, React.createElement("form", {
                                  className: "card comment-form"
                                }, React.createElement("div", {
                                      className: "card-block"
                                    }, React.createElement("textarea", {
                                          className: "form-control",
                                          placeholder: "Write a comment...",
                                          rows: 3
                                        })), React.createElement("div", {
                                      className: "card-footer"
                                    }, React.createElement("img", {
                                          className: "comment-author-img",
                                          src: "http://i.imgur.com/Qr71crq.jpg"
                                        }), React.createElement("button", {
                                          className: "btn btn-sm btn-primary"
                                        }, "Post Comment"))), React.createElement("div", {
                                  className: "card"
                                }, React.createElement("div", {
                                      className: "card-block"
                                    }, React.createElement("p", {
                                          className: "card-text"
                                        }, "With supporting text below as a natural lead-in to additional content.")), React.createElement("div", {
                                      className: "card-footer"
                                    }, React.createElement("a", {
                                          className: "comment-author",
                                          href: ""
                                        }, React.createElement("img", {
                                              className: "comment-author-img",
                                              src: "http://i.imgur.com/Qr71crq.jpg"
                                            })), "&nbsp;", React.createElement("a", {
                                          className: "comment-author",
                                          href: ""
                                        }, "Jacob Schmidt"), React.createElement("span", {
                                          className: "date-posted"
                                        }, "Dec 29th"))), React.createElement("div", {
                                  className: "card"
                                }, React.createElement("div", {
                                      className: "card-block"
                                    }, React.createElement("p", {
                                          className: "card-text"
                                        }, "With supporting text below as a natural lead-in to additional content.")), React.createElement("div", {
                                      className: "card-footer"
                                    }, React.createElement("a", {
                                          className: "comment-author",
                                          href: ""
                                        }, React.createElement("img", {
                                              className: "comment-author-img",
                                              src: "http://i.imgur.com/Qr71crq.jpg"
                                            })), "&nbsp;", React.createElement("a", {
                                          className: "comment-author",
                                          href: ""
                                        }, "Jacob Schmidt"), React.createElement("span", {
                                          className: "date-posted"
                                        }, "Dec 29th"), React.createElement("span", {
                                          className: "mod-options"
                                        }, React.createElement("i", {
                                              className: "ion-edit"
                                            }), React.createElement("i", {
                                              className: "ion-trash-a"
                                            }))))))));
    });
  return newrecord;
}

exports.component = component;
exports.show      = show;
exports.make      = make;
/* component Not a pure module */
