// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Header");

function show(prim) {
  return prim;
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "editor-page"
                }, React.createElement("div", {
                      className: "container page"
                    }, React.createElement("div", {
                          className: "row"
                        }, React.createElement("div", {
                              className: "col-md-10 offset-md-1 col-xs-12"
                            }, React.createElement("form", undefined, React.createElement("fieldset", undefined, React.createElement("fieldset", {
                                          className: "form-group"
                                        }, React.createElement("input", {
                                              className: "form-control form-control-lg",
                                              placeholder: "Article Title",
                                              type: "text"
                                            })), React.createElement("fieldset", {
                                          className: "form-group"
                                        }, React.createElement("input", {
                                              className: "form-control",
                                              placeholder: "What's this article about?",
                                              type: "text"
                                            })), React.createElement("fieldset", {
                                          className: "form-group"
                                        }, React.createElement("textarea", {
                                              className: "form-control",
                                              placeholder: "Write your article (in markdown)",
                                              rows: 8
                                            })), React.createElement("fieldset", {
                                          className: "form-group"
                                        }, React.createElement("input", {
                                              className: "form-control",
                                              placeholder: "Enter tags",
                                              type: "text"
                                            }), React.createElement("div", {
                                              className: "tag-list"
                                            })), React.createElement("button", {
                                          className: "btn btn-lg pull-xs-right btn-primary",
                                          type: "button"
                                        }, "Publish Article")))))));
    });
  return newrecord;
}

exports.component = component;
exports.show      = show;
exports.make      = make;
/* component Not a pure module */
