// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';


function doSomething(args) {
  console.log(args);
  return "expectedOutput";
}

exports.doSomething = doSomething;
/* No side effect */
