// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Header");

function show(prim) {
  return prim;
}

function make(router, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var goToRegistration = function ($$event) {
        $$event.preventDefault();
        router.setRoute("/register");
        return /* () */0;
      };
      return React.createElement("div", undefined, React.createElement("nav", {
                      className: "navbar navbar-light"
                    }, React.createElement("div", {
                          className: "container"
                        }, React.createElement("a", {
                              className: "navbar-brand",
                              href: "index.html"
                            }, "conduit"), React.createElement("ul", {
                              className: "nav navbar-nav pull-xs-right"
                            }, React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      className: "nav-link active",
                                      href: "#/"
                                    }, "Home")), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      className: "nav-link",
                                      href: "#/article/create"
                                    }, React.createElement("i", {
                                          className: "ion-compose"
                                        }), " New Post")), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      className: "nav-link",
                                      href: "#/settings"
                                    }, React.createElement("i", {
                                          className: "ion-gear-a"
                                        }), " Settings")), React.createElement("li", {
                                  className: "nav-item"
                                }, React.createElement("a", {
                                      className: "nav-link",
                                      href: "#",
                                      onClick: goToRegistration
                                    }, "Sign up"))))));
    });
  return newrecord;
}

exports.component = component;
exports.show      = show;
exports.make      = make;
/* component Not a pure module */
