// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.reducerComponent("Register");

function show(prim) {
  return prim;
}

function register() {
  return /* Register */1;
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var state = param[/* state */4];
      return React.createElement("div", {
                  className: "auth-page"
                }, React.createElement("div", {
                      className: "container page"
                    }, React.createElement("div", {
                          className: "row"
                        }, React.createElement("div", {
                              className: "col-md-6 offset-md-3 col-xs-12"
                            }, React.createElement("h1", {
                                  className: "text-xs-center"
                                }, "Sign up"), React.createElement("p", {
                                  className: "text-xs-center"
                                }, React.createElement("a", {
                                      href: ""
                                    }, "Have an account?")), React.createElement("ul", {
                                  className: "error-messages"
                                }, React.createElement("li", undefined, "That email is already taken")), React.createElement("form", undefined, React.createElement("fieldset", {
                                      className: "form-group"
                                    }, React.createElement("input", {
                                          className: "form-control form-control-lg",
                                          placeholder: "Your Name",
                                          type: "text",
                                          value: state[/* name */0]
                                        })), React.createElement("fieldset", {
                                      className: "form-group"
                                    }, React.createElement("input", {
                                          className: "form-control form-control-lg",
                                          placeholder: "Email",
                                          type: "text",
                                          value: state[/* email */1]
                                        })), React.createElement("fieldset", {
                                      className: "form-group"
                                    }, React.createElement("input", {
                                          className: "form-control form-control-lg",
                                          placeholder: "Password",
                                          type: "password",
                                          value: state[/* password */2]
                                        })), React.createElement("button", {
                                      className: "btn btn-lg btn-primary pull-xs-right",
                                      onClick: Curry._1(param[/* reduce */3], register)
                                    }, "Sign up"))))));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* name */"",
              /* email */"",
              /* password */""
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (action !== 0) {
        return /* UpdateWithSideEffects */Block.__(3, [
                  /* record */[
                    /* name */state[/* name */0],
                    /* email */"fake",
                    /* password */state[/* password */2]
                  ],
                  (function () {
                      console.log(state);
                      return /* () */0;
                    })
                ]);
      } else {
        return /* NoUpdate */0;
      }
    });
  return newrecord;
}

exports.component = component;
exports.show      = show;
exports.register  = register;
exports.make      = make;
/* component Not a pure module */
